name: tddns Development CI

on:
  push:
    branches:
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "release/*"

jobs:
  build-binary:
    name: Build Development Binary
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-slim@sha256:f6e2cfac5cf956ea044b4bd75e6397b4372ad88fe00908045e9a0d21712ae3ba
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Update repositories
        run: apt-get update
      - name: Install dependencies
        run: apt-get install --no-install-recommends -y gcc libc6-dev libcurl4-openssl-dev make pkg-config
      - name: Build binary
        run: make tddns

  build-container:
    name: Build Runtime Container
    runs-on: ubuntu-latest
    steps:
      - name: Prepare metadata
        id: meta
        run: |
          echo "PUSH=${{ github.ref == 'refs/heads/main' }}" >>$GITHUB_OUTPUT
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >>$GITHUB_OUTPUT
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "TAGS=${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:latest,${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:$SHORT_SHA" >>$GITHUB_OUTPUT
          else
            echo "TAGS=${{ vars.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:latest" >>$GITHUB_OUTPUT
          fi
      - name: Run actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run docker/setup-buildx-action
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Run docker/login-action
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get build date
        id: build_date
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >>"${GITHUB_OUTPUT}"
      - name: Build Container
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ steps.meta.outputs.PUSH }}
          load: true
          tags: ${{ steps.meta.outputs.TAGS }}
          build-args: |
            VERSION=${{ github.sha }}
            COMMIT_SHA=${{ github.sha }}
            BUILD_DATE=${{ steps.build_date.outputs.date }}
