name: Security Analysis

on:
  push:
    branches:
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "release/*"
  schedule:
    - cron: "23 3 * * *" # Daily at 03:23 UTC

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-slim
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Run actions/checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Update repositories
        run: apt-get update
      - name: Install dependencies
        run: apt-get install --no-install-recommends -y gcc libc6-dev libcurl4-openssl-dev make pkg-config
      - name: Run github/codeql-action/init
        uses: github/codeql-action/init@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4
        with:
          languages: c-cpp
          build-mode: manual
          queries: security-and-quality
      - name: Build
        env:
          CC: gcc
        run: make clean all
      - name: Run github/codeql-action/analyze
        uses: github/codeql-action/analyze@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4
        with:
          category: "/language:c"
